# Generated by Django 6.0.4 on 2026-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='unlock_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
